services:
  dbt-erd-viewer:
    build: .
    ports:
      - "1000:1000"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_PORT=1000
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped 